version: '3.8'
services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - backend
    

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - mongooese
  

  mongooese:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
